<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE factura [

<!ELEMENT factura (datosEmisor,datosCliente,detallesFactura)>
<!ELEMENT datosEmisor (nombre,CIF,telefono)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT CIF (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>


<!ELEMENT datosCliente (nombre2,CIF2,telefono2)>
<!ELEMENT nombre2 (#PCDATA)>
<!ELEMENT CIF2 (#PCDATA)>
<!ELEMENT telefono2 (#PCDATA)>

<!ELEMENT detallesFactura (articulo)*>
<!ATTLIST detallesFactura importe CDATA #REQUIRED>
<!ATTLIST detallesFactura numero CDATA #REQUIRED>
<!ATTLIST detallesFactura fecha CDATA #REQUIRED>

<!ELEMENT articulo (descripcion,cantidad,oferta,pvp)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT cantidad (#PCDATA)>
<!ELEMENT oferta EMPTY>
<!ELEMENT pvp (#PCDATA)>

<!ATTLIST articulo codigo_articulo CDATA #REQUIRED>
<!ATTLIST articulo tipo (Libro | DVD | Varios) #IMPLIED>

]>

<factura>

    <datosEmisor>

        <nombre>Librería Pérez</nombre>
        <CIF>44555666B</CIF>
        <telefono>777888999</telefono>

    </datosEmisor>


    <datosCliente>

        <nombre2>Biblioteca Xantrea</nombre2>
        <CIF2>33111222A</CIF2>
        <telefono2>333999444</telefono2>


    </datosCliente>


    <detallesFactura importe = '85' numero="27" fecha= "18/12/2023">

        <articulo codigo_articulo="AW7" tipo = "Libro">
            <descripcion>Analítica Web 2.0</descripcion>
            <cantidad>1</cantidad>
            <oferta></oferta>
            <pvp>25</pvp>
        </articulo>

        <articulo codigo_articulo="CP5" tipo = "DVD">
            <descripcion>Curso de HTML</descripcion>
            <cantidad>2</cantidad>
            <oferta></oferta>
            <pvp>30</pvp>
        </articulo>


    </detallesFactura>


</factura>
