<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE aeropuerto [
    <!ELEMENT aeropuerto (vuelo,FechaSalida)>
    <!ATTLIST aeropuerto nombre CDATA >
    <!ELEMENT FechaSalida (#PCDATA) #REQUIRED >
    <!ELEMENT vuelo (diario,origen,destino,horaSalida,horaLLegada)>
    <!ATTLIST vuelo codigo CDATA #REQUIRED>
    <!ATTLIST vuelo estado (E|R|C) 'E'>

    <!ELEMENT diario EMPTY>
    <!ELEMENT origen (#PCDATA)>
    <!ELEMENT destino (#PCDATA)>
    <!ELEMENT horaSalida (#PCDATA)>
    <!ELEMENT horaLlegada (#PCDATA)>
]>


<aeropuerto nombre = "JKF">
    <FechaSalida>20/12/2023</FechaSalida>

    <vuelo codigo = 'V22' estado = 'R' >
        <diario></diario>
        <origen>New York</origen>
        <destino>Chicago</destino>
        <horaSalida>9:30</horaSalida>
        <horaLLegada>11:30</horaLLegada>
    </vuelo>
    
    <vuelo codigo ='V23' estado = 'C'>
        <diario></diario>
        <origen>New York</origen>
        <destino>Miami</destino>
        <horaSalida>10:15</horaSalida>
        <horaLLegada>11:15</horaLLegada>
    </vuelo>
    
    </aeropuerto>
